# Generated by Django 5.0.7 on 2024-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Doctor care', 'Doctor care'), ('Pet care', 'Pet care'), ('Medical services', 'Medical services')], default='Doctor care', max_length=50),
        ),
    ]
